Translation into Japanese
msawired/OpenProcessing-i18n pull request #4
Opened 2021-02-17 11:58 UTC by reona396

I translated into Japanese.
I checked by beta.openprocessing.org .
I think that it needs some reviewers who uses Japanese to check for anything unnatural.

日本語へ翻訳しました。
beta.openprocessing.org での動作チェック済です。
不自然なところがないかチェックするために、何人か日本語使用者のレビューを入れていただけると助かります。

2021-02-19 15:20 UTC, msawired requested changes
Thank you for all the help!
I also added some new phrases waiting for translation. You can find them on the master branch.

2021-02-19 15:20 UTC, msawired commented on lang.json
> +			"ja": "-",
Is there a word we can use instead of '-'? I am trying to be little more wordy and conversational on the website, in contrast to the very transactional nature of the coding world. Something you would use describing a novel written by someone, such as "Norwegian Wood *by* Murakami"?

2021-02-19 15:20 UTC, msawired commented on lang.json
> +			"ja": "フォロー中",
Can you include {n} here?

2021-02-19 15:33 UTC, msawired commented
I resolved the merge conflicts, and merged new updates from master branch. Can you take a look at `"ja": null` phrases? Those are the new ones.

2021-02-20 19:14 UTC, merged

2021-02-21 00:38 UTC, deconbatch commented on lang.json
> +			"ja": "-",
I think the word 'by' will be suitable. It will be OK with most Japanese. No need to translate.

2021-02-21 00:41 UTC, deconbatch commented on lang.json
>  			"pt": null
null -> "例：{0}"

2021-02-21 00:42 UTC, deconbatch commented on lang.json
>  			"pt": "Saiba mais sobre"
null -> "さらに詳しく"

2021-02-21 00:51 UTC, deconbatch commented on lang.json
>  			"pt": "Compartilhe a URL da sua aula com o código junto."
コーディングを楽しむために → 共同作業のために
とか？

2021-02-21 00:51 UTC, deconbatch commented on lang.json
>  			"pt": "Convide sua turma para programar juntos."
コーディングを楽しむために → 共同作業のために

2021-02-21 00:55 UTC, deconbatch commented on lang.json
>  			"pt": "Centralizar esboço e corresponder a cor de fundo."
背景色を「似合う」ものにするという意味だと思いますが、長くなるので、
背景色を同じ色にする → 背景色をつける
でどうでしょう？

2021-02-21 01:12 UTC, deconbatch commented on lang.json
>  			"pt": "Prévia das 20 versões mais recentes são resumidas."
「直近20バージョンより前は集約して表示してます」ということかなと思いますが何と言ったものか。
"直近の20バージョン以外は集約されています"
でどうでしょう？

2021-02-21 01:44 UTC, deconbatch commented on lang.json
>  		},
にカスタムライブラリ → とカスタムライブラリ
Plus+メンバーになるとカスタムライブラリ… ですよね。

2021-02-21 01:44 UTC, deconbatch commented on lang.json
>  			"pt": null
null → "タイトル"

2021-02-21 01:46 UTC, deconbatch commented on lang.json
> +			"ja": null,
null → "説明"

2021-02-21 01:47 UTC, deconbatch commented on lang.json
>  			"pt": null
null → "操作方法"

2021-02-21 01:47 UTC, deconbatch commented on lang.json
> +			"ja": null,
null → "タグ"

2021-02-21 01:48 UTC, deconbatch commented on lang.json
> +			"ja": null,
null → "ライセンス"

2021-02-21 01:50 UTC, deconbatch commented on lang.json
>  			"pt": null
null → "下書き"

2021-02-21 01:51 UTC, deconbatch commented on lang.json
>  			"pt": null
null → "フィードには表示されませんが、あなたのプロフィールページには表示されます。"

2021-02-21 01:52 UTC, deconbatch commented on lang.json
>  			"pt": null
null → "誰がこのスケッチを見ることができますか？"

2021-02-21 01:52 UTC, deconbatch commented on lang.json
>  			"pt": null
null → "誰がこのコードを見ることができますか？"

2021-02-21 01:53 UTC, deconbatch commented on lang.json
>  			"pt": null
null → "誰がコメントを付けることができますか？"

2021-02-21 01:53 UTC, deconbatch commented on lang.json
>  			"pt": null
null → "誰でも"

2021-02-21 02:06 UTC, deconbatch commented on lang.json
>  			"pt": null
null → "私のクラス"

2021-02-21 02:07 UTC, deconbatch commented on lang.json
> +			"ja": null,
null → "あなたのクラスの先生と生徒のみ"

2021-02-21 02:07 UTC, deconbatch commented on lang.json
>  			"pt": null
null → "私の先生"

2021-02-21 02:07 UTC, deconbatch commented on lang.json
>  			"pt": null
null → "あなたのクラスの先生のみ"

2021-02-21 02:07 UTC, deconbatch commented on lang.json
>  			"pt": null
null → "私だけ"

2021-02-21 02:08 UTC, deconbatch commented on lang.json
>  			"pt": null
null → "プライベートURL"

2021-02-21 02:11 UTC, deconbatch commented on lang.json
>  			"pt": null
null → "誰が見れるかの設定にかかわらず、このURLでスケッチをシェアできます。"

2021-02-21 02:11 UTC, deconbatch commented on lang.json
>  			"pt": null
null → "作成"

2021-02-21 02:12 UTC, deconbatch commented on lang.json
> +			"ja": null,
null → "プライベートURLを作成するにはスケッチを保存してください。"

2021-02-21 02:13 UTC, deconbatch commented on lang.json
> +			"ja": null,
null → "スケッチを削除しますか？"

2021-02-24 13:30 UTC, reona396 commented on lang.json
> +			"ja": "-",
It's true that "by" doesn't need to be translated. 
I thought it is difficult to translate the prepositions, but it seems that the ones that are often used in Japanese can be left as they are.
 For the same reason, I will use the same notation for "from", which indicates "place of residence."

たしかに「by」は翻訳しなくていいですね。
前置詞の翻訳は難しいなぁと思っていたんですが、日本語でもよく使うものはそのままで良さそうです。
同様の事情で「居住地」を示す「from」もそのままの表記にしようと思います。

2021-02-24 13:34 UTC, reona396 commented on lang.json
> +			"ja": "フォロー中",
Sorry, I made a mistake. I'll fix it.

2021-02-24 13:35 UTC, reona396 commented on lang.json
>  			"pt": null
Thank you ありがとうございます！

2021-02-24 13:36 UTC, reona396 commented on lang.json
>  			"pt": "Saiba mais sobre"
Thank you ありがとうございます！

2021-02-24 13:37 UTC, reona396 commented on lang.json
>  			"pt": "Compartilhe a URL da sua aula com o código junto."
Thank you ありがとうございます！

2021-02-24 13:38 UTC, reona396 commented on lang.json
>  			"pt": "Centralizar esboço e corresponder a cor de fundo."
ありがとうございます、採用させていただきます！

2021-02-24 13:40 UTC, reona396 commented on lang.json
>  			"pt": "Prévia das 20 versões mais recentes são resumidas."
助かります！！採用させていただきます！！

2021-02-24 13:45 UTC, reona396 commented on lang.json
>  		},
「{0} になるとカスタムライブラリの追加〜ができるようになります！」ってことですかね？

2021-02-24 13:46 UTC, reona396 commented on lang.json
>  			"pt": null
この訳はスマートでいいですね…勉強になります

2021-02-24 13:47 UTC, reona396 commented on lang.json
>  			"pt": null
ありがとうございます！！thanks!

2021-02-24 13:49 UTC, reona396 commented on lang.json
>  			"pt": null
ありがとうございます、ちょっと長いかなと思ったので「誰がコメントできますか？」でいきます

2021-02-24 13:50 UTC, reona396 commented on lang.json
>  			"pt": null
ここ微妙ですが、「自分のクラス」でいいかな〜と思っています。悩みどころですね…

2021-02-24 13:52 UTC, reona396 commented on lang.json
>  			"pt": null
ここ難しいですね…いったん「先生」にしてみます。
"私の"or"自分の"以外の先生が登場するかな？という観点です。

2021-02-24 13:53 UTC, reona396 commented on lang.json
>  			"pt": null
ここもめちゃくちゃ難しい…(さっきから対象の話で悩みすぎ)
「自分のクラスの先生のみ」でいってみます。

2021-02-24 13:54 UTC, reona396 commented on lang.json
>  			"pt": null
「自分のみ」にしてみます！

2021-02-24 13:56 UTC, reona396 commented on lang.json
>  			"pt": null
名訳！ありがとうございます！！ thank you!

2021-03-10 04:24 UTC, msawired commented on lang.json
> +			"ja": "-",
that's great, thank you! Working on some updates on the profile page which will remove "from" word anyways. Cheers!

2021-03-10 04:30 UTC, msawired commented on lang.json
>  		},
To clarify: The original is a mix of two sections. "Join Plus+ to add custom libraries, private sketches, and more!". 
"Join Plus+" is a link, and comes from general.joinPlus. I assumed it would be possible to join such phrases in other languages as well, but let me know if it doesn't make sense in Japanese.

2021-03-10 04:32 UTC, msawired commented on lang.json
>  			"pt": null
This seems to be set to "null" back. Can you update?

2021-03-10 04:32 UTC, msawired commented on lang.json
>  			"pt": null
same here.

2021-03-10 04:34 UTC, msawired commented on lang.json
>  			"pt": null
This is displayed when user is a teacher or a student, and signed up to a class on OpenProcessing. When selected, sketch is only accessible by teacher or students of their classes.

2021-03-10 04:35 UTC, msawired commented on lang.json
>  			"pt": null
let me know if there is anything I can clarify here.

2021-03-10 04:35 UTC, msawired commented on lang.json
>  			"pt": null
let me know if there is anything I can clarify here.

2021-03-10 04:38 UTC, msawired commented on lang.json
>  			"pt": null
Ignore what I said. All looks good, thank you!

2021-03-10 13:50 UTC, reona396 commented on lang.json
>  		},
@msawired Thank you for  your explanations!
I'll fix it according to the information.